### ISSUE TITLE
Comments doesn't post correctly anymore

### ISSUE THREAD

**Issue by FredSoderberg** [Cykelinspektionen/MjukvaruProjekt#113]
Once you post it to the server side it doesn't get added correctly. No changes on client side has been done to trigger this. Probably due to model changes on server side.

**Comment by FredSoderberg** [comment]
can't replicate anymore @erikajansson1

**Comment by HThorsell** [comment]
Me neither. Is this resolved?

**Comment by FredSoderberg** [comment]
Guess so, might have been trouble an ad that was outdated? Anyways can’t replicate so I’m closing
