### ISSUE TITLE
Adrians android phone doesn't show taken pictures

### ISSUE THREAD

**Issue by FredSoderberg** [Cykelinspektionen/MjukvaruProjekt#115]
yeeee......... he has a android 8.0 oreo samsung a3

**Comment by adrian621** [comment]
Fungerar inte för Jakob heller :/

**Comment by jakobemilandersson** [comment]
Emulator: Nexus 5X, funkar delvis men ibland måste man ta kort 3-4 gånger innan det funkar 🐈

**Comment by FredSoderberg** [comment]
skaffa en icke potatis lur

**Comment by adrian621** [comment]
icke-potatislur*

**Comment by FredSoderberg** [comment]
haha! Yeah same on my galaxy, have to look at this later, might be how android stores images

**Comment by jakobemilandersson** [comment]
@adrianTyrevall , it seems to be working without any problem now when the camera has been updated! Does it work for you now too? 😄

**Comment by jakobemilandersson** [comment]
One weird thing is that when I run the application "clean" (without any previous saved state), giving access to the camera results in "promise rejection"-errors. But when I give access to reading from my albums, the camera suddenly got the permissions it needs!

**Comment by FredSoderberg** [comment]
Could be an effect of my changes to imagepicker camera, might have forgotten to implement the “ask” permission part for the camera... but they should be separate permissions(?). Ahh well one step forward and one back :P

**Comment by FredSoderberg** [comment]
@adrianTyrevall still broken?
