### ISSUE TITLE
Flag comment if its a response to another comment

### ISSUE THREAD

**Issue by FredSoderberg** [Cykelinspektionen/MjukvaruProjekt#119]
There needs to be in the comment model a flag if its a response to another comment and that comments ID

**Comment by HThorsell** [comment]
I've pushed an implementation to the server with the following changes:

- Add comment can now be done with the additional optional parameter 'replyCommentId' which should be an Id of another comment.
- To see if a comment is a reply to another comment, check if the field replyCommentId is undefined. Undefined means it is not a reply. If the field is defined it should be an Id an Id, that Id is then the comment which is replied to.
