### ISSUE TITLE
header in everywhere except bike information has dropped down for some reason

### ISSUE THREAD

**Issue by FredSoderberg** [Cykelinspektionen/MjukvaruProjekt#189]

**Comment by adrian621** [comment]
Vilken device och androidverison körde du på? Ser bra ut för mig och Erika

**Comment by FredSoderberg** [comment]
Ahh can be the “lip” on the iPhone X’s... but still weird since it works on the other headers. The ones in bikeinformation and so forth

**Comment by FredSoderberg** [comment]
solved this
