### ISSUE TITLE
Description is hidden under keyboard in addbike, related to the submitting button that also is not visible??

### ISSUE THREAD

**Issue by erikajansson1** [Cykelinspektionen/MjukvaruProjekt#196]
use keyboardVerticalOffset to solve this

**Comment by FredSoderberg** [comment]
Alternative: check how comment submit field is structured, 'KeyboardAvoidingView'

**Comment by FredSoderberg** [comment]
this might be an iOS bug that is connected to submit button being dropped behind everything... margin gone crazy? ;)
anyways it works fine on android... or it has unnecessary amount of free space at the bottom but doesn't matter

**Comment by FredSoderberg** [comment]
there is a margin in container that fixes this on android... but not on ios where the tab is higher
