### ISSUE TITLE
Implement pointsystem to gamification

### ISSUE THREAD

**Issue by erikajansson1** [Cykelinspektionen/MjukvaruProjekt#72]

**Comment by FredSoderberg** [comment]
Includes making all the buttons for closing and promoting tips and bicycles

**Comment by FredSoderberg** [comment]
found bike can be close by everybody.
stolen bike only closed by owner

**Comment by FredSoderberg** [comment]
Issue entails creating front end calls to backend for attributing points based on user actions client side.

- [x] Thumbs up, gives point to commentator
- [x] Thumbs down, nothing right now
- [x] Warning when closing add
- [x] Press found bike on comment in my stolen. points to comment, buttons shouldn't be visible in browser bikes comments. unless its current users bike.
- [x] Press Found bike in my lost bike ad, a large button top right. No points given. buttons shouldn't be visible in browser bikes. unless its current users bike.

- [x] Press Found bike on "Found bikes", closes ad and gives point to user. If ad owner does this, no points are given.
- [x] Press found bike on "Found bikes" comment in ad closes and give points to the comment and add owner, 5 points each apparently?

**Comment by FredSoderberg** [comment]
Will include a merge from #48, delay is to expected

**Comment by FredSoderberg** [comment]
Blocked until backend endpoints generate requested values

**Comment by FredSoderberg** [comment]
There is some more testing but mainly waiting for #110

**Comment by HThorsell** [comment]
#110 is now closed!
