### ISSUE TITLE
Endpoint for adding or subtracting gamescore

### ISSUE THREAD

**Issue by FredSoderberg** [Cykelinspektionen/MjukvaruProjekt#93]
Suggestion is that the same end point can take either bike_score or thumb_score with a value, either negative or positive. ex {bike_score:5}

**Comment by HThorsell** [comment]
POST request to:
http://bikeify.herokuapp.com/users/updatescore/

Parameters:
	user_name: String
	bike_score: String/Number (optional)
	thumb_score: String/Number (optional)

Increments the user bike or thumb score by the provided amount. Negative amount decreases the score. The new total score is calculated as bike+thumb score and is updated on changes.

Returns the updated user.
