### ISSUE TITLE
Compress images befores sending them to the server

### ISSUE THREAD

**Issue by lucatonile** [Cykelinspektionen/MjukvaruProjekt#97]

**Comment by jakobemilandersson** [comment]
Is this for preadd or for addbike? 😄 
and @lucatonile @HThorsell @adrianTyrevall , is there any resolution that is prefererad? 😸

**Comment by lucatonile** [comment]
@jakobemilandersson, only for addbike and updateprofile pic atm. not sure if preaddbike pic should be compressed at all? no preferred resolution really

**Comment by lucatonile** [comment]
@jakobemilandersson, oh confused this card with the compression on server-side! I think we decided that all compression will be done on the server, so this card is kind of obsolete

**Comment by lucatonile** [comment]
compression is handled on server
